services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /srv/docker/uptime-kuma/data:/app/data

  loki:
    image: grafana/loki:3.6.4
    container_name: loki
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./logging/loki/config.yaml:/etc/loki/config.yaml:ro
      - /srv/docker/monitoring/loki:/loki

  promtail:
    image: grafana/promtail:3.6.0
    container_name: promtail
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
    depends_on:
      - loki
    volumes:
      - ./logging/promtail/config.yaml:/etc/promtail/config.yaml:ro
      - /srv/docker/monitoring/promtail:/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro

  grafana:
    image: grafana/grafana-oss:12.3.1-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3010:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
    depends_on:
      - loki
    volumes:
      - /srv/docker/monitoring/grafana:/var/lib/grafana
      - ./logging/grafana/provisioning:/etc/grafana/provisioning:ro
